pipeline {
    agent any
    environment {
        OCI_AUTH_TOKEN = credentials('oke-jenkins-secret')
        KUBECONFIG = '/home/ec2-user/.kube/config'
    }
    stages {
        stage('Deploy to OKE') {
            steps {
                script {
                        sh '''
                        sudo KUBECONFIG=/home/ec2-user/.kube/config /usr/local/bin/kubectl apply -f deployment.yaml
                        '''
                }
            }
        }
    }
}
